services:
  redis:
    image: redis:7.2.4
    container_name: litellm-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass myredissecret
    volumes:
      - redis_data:/data

volumes:
  redis_data: